version: '3.8'

services:
  redis:
    image: redis:latest
    #container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - virtual-office-local

  postgres:
    image: postgres:15
    #container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/initdb/postgres:/docker-entrypoint-initdb.d
    networks:
      - virtual-office-local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-main}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    #container_name: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts/initdb/mongo:/docker-entrypoint-initdb.d
    networks:
      - virtual-office-local

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    #container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "22181:2181"
    networks:
      - virtual-office-local

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    #container_name: kafka
    ports:
      - "29092:29092" # for host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - virtual-office-local

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    #container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "18081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: docker-network
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - virtual-office-local

volumes:
  redis_data:
  postgres_data:
  mongo_data:

networks:
  virtual-office-local:
    driver: bridge
