server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: http://localhost:8081
          predicates:
            - Path=/events/**

        - id: shadow-ledger-service
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/**

        - id: drift-correction-service
          uri: http://localhost:8083
          predicates:
            - Path=/drift-check/**
            - Path=/correct/**
